### ISSUE TITLE
Cannot collect captures of apitrace replay

### ISSUE THREAD

**Issue by marcinslusarz** [baldurk/renderdoc#1883]
## Description

RenderDoc cannot collect captures of apitrace (https://github.com/apitrace/apitrace) in replay mode.

## Steps to reproduce

Set "Executable Path" to apitrace.
Set "Command-line arguments" to "replay -b $path_to_trace_file".
Click "Launch".
When apitrace is running status window shows that the connection status is "established" and API is "None".
Captures counter in the overlay increases on F12, but after apitrace window closes, the application tab also closes.

### Workaround

Use glretrace instead of apitrace replay

## Environment

* RenderDoc version: 1.7
* Operating System: Linux
* Graphics API: OpenGL
* apitrace 1b3c83371ae34a894cff6168e765098f91c6620a

[DiagnosticLogFile.txt](https://github.com/baldurk/renderdoc/files/4617855/log.txt)

**Comment by baldurk** [comment]
Capturing apitrace's replay was fine, the problem was that apitrace runs a child process to do the replay and on linux the child processes weren't properly propagated up to the UI. That commit should fix it so they are displayed.

**Comment by marcinslusarz** [comment]
Still doesn't work for me. (on f39e05a4d634bd9eccc885cfbe2e19c33e77be6c, which includes d7ed861f9b674bc17f00c47bb76c6b98331b02c5)

[renderdoc_after_fix.log](https://github.com/baldurk/renderdoc/files/4677158/renderdoc_after_fix.log)

I can't reopen this issue.

**Comment by baldurk** [comment]
Did you navigate to the child process? The connection window should now show any child processes which you can then select to open a new connection to that process:

![image](https://user-images.githubusercontent.com/661798/82813839-c9b6d000-9e8d-11ea-9716-98282cee9558.png)

**Comment by marcinslusarz** [comment]
When apitrace replay is in progress the API label says "None".
The apitrace tab closes as soon as apitrace finishes.

**Comment by marcinslusarz** [comment]
The UI for tracing "apitrace replay" works a bit differently than for "glretrace", and that's what confused me.

Now that I understand the difference I can say it works.
