### ISSUE TITLE
Failed to capture frame in UE4.25 without error message

### ISSUE THREAD

**Issue by jialuchen96** [baldurk/renderdoc#2086]
## Description
When I enabled RenderDocPlugin in UE4.25 and pressed the button 
![image](https://user-images.githubusercontent.com/72073323/97937517-e69aec00-1db9-11eb-901e-2f000d7133dd.png) to capture the next frame, the RenderDoc was automatically launched but I could not inspect the frame.
The Diagnostic Log was like this:
![image](https://user-images.githubusercontent.com/72073323/97937988-2f06d980-1dbb-11eb-95a5-c21f824c338c.png)

## Steps to reproduce
1. install RenderDoc v1.8
2. open any project in UE4.25
3. open Plugins Browser and enable RenderDocPlugin
4. Restart UE4.25 project and  pressed the renderdoc button 
![image](https://user-images.githubusercontent.com/72073323/97938468-6c1f9b80-1dbc-11eb-9e99-930b740c537f.png)

## Environment

RenderDoc version: v1.8
Operating System: Windows 10
Graphics API: D3D11

ps: I used RenderDoc v1.8 because UE4.25 crashed when using RenderDoc v1.10.

**Comment by baldurk** [comment]
Can you please re-test this with the latest nightly build? I understand that v1.10 doesn't work but there are many bugs that have been fixed since v1.8.

**Comment by jialuchen96** [comment]
> Can you please re-test this with the latest nightly build? I understand that v1.10 doesn't work but there are many bugs that have been fixed since v1.8.

I re-tested it with the latest nightly build, but it still failed to capture the frame.
![image](https://user-images.githubusercontent.com/72073323/97983962-06113380-1e11-11eb-8387-cd22e18c2861.png)

**Comment by jialuchen96** [comment]
> Can you please re-test this with the latest nightly build? I understand that v1.10 doesn't work but there are many bugs that have been fixed since v1.8.

I re-tested it with the latest nightly build, but it still failed to capture the frame.
![image](https://user-images.githubusercontent.com/72073323/97984322-951e4b80-1e11-11eb-9023-1124e3ccd695.png)

**Comment by baldurk** [comment]
Posting a screenshot of a log file is the worst way to convey text, in future you should save the log to disk and upload it as an attachment.

That log also doesn't show anything, all it shows is that RenderDoc has been started and has connected to the UE4 editor process. What happens if you trigger a capture after this point? Or alternatively launch the UE4 editor from renderdoc instead of using the plugin, so that the log contains all information including any capture made prior to RenderDoc connecting.

**Comment by jialuchen96** [comment]
> Posting a screenshot of a log file is the worst way to convey text, in future you should save the log to disk and upload it as an attachment.
> 
> That log also doesn't show anything, all it shows is that RenderDoc has been started and has connected to the UE4 editor process. What happens if you trigger a capture after this point? Or alternatively launch the UE4 editor from renderdoc instead of using the plugin, so that the log contains all information including any capture made prior to RenderDoc connecting.

In fact that's all the log information.  I tried connecting to UE4 editor from renderdoc and pressed the button 'Capture Frames Immediately'.
![image](https://user-images.githubusercontent.com/72073323/98061392-bf5e2080-1e86-11eb-9212-75ca86412c6a.png)
but there was nothing new in the log file.
[log11-4.log](https://github.com/baldurk/renderdoc/files/5485134/log11-4.log)

**Comment by baldurk** [comment]
The screenshots shows that the capture has started but not completed. Is the editor still rendering and presenting?

Please run the editor through RenderDoc instead of allowing the plugin integration to load RenderDoc, and post the log from that run. That will include the logging information from the capture process itself.

**Comment by jialuchen96** [comment]
> The screenshots shows that the capture has started but not completed. Is the editor still rendering and presenting?
> 
> Please run the editor through RenderDoc instead of allowing the plugin integration to load RenderDoc, and post the log from that run. That will include the logging information from the capture process itself.

Thank you for your help! I found a way to successfully capture frames in UE4 editor.
1. Open any project with RenderDocPlugin enabled in UE4.25.
2. Run qrenderdoc.exe，choose 'File' - 'Inject into Process', find UE4 editor and Inject.
3. Press the renderdoc button in UE4 editor. Do not press the button 'Capture Frames Immediately' in renderdoc otherwise you'll get the entire editor interface.
