### ISSUE TITLE
does not build - error: dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by Marqin** [baldurk/renderdoc#274]
**does not build - error: dereferencing type-punned pointer will break strict-aliasing rules** in `renderdoc/maths/half_convert.h` on line 125.

full error:

```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marqin/renderdoc/src/renderdoc-0.29/build
make[1]: Wejście do katalogu '/home/marqin/renderdoc/src/renderdoc-0.29/build'
make[2]: Wejście do katalogu '/home/marqin/renderdoc/src/renderdoc-0.29/build'
make[3]: Wejście do katalogu '/home/marqin/renderdoc/src/renderdoc-0.29/build'
make[3]: Wejście do katalogu '/home/marqin/renderdoc/src/renderdoc-0.29/build'
make[3]: Opuszczenie katalogu '/home/marqin/renderdoc/src/renderdoc-0.29/build'
make[3]: Opuszczenie katalogu '/home/marqin/renderdoc/src/renderdoc-0.29/build'
make[3]: Wejście do katalogu '/home/marqin/renderdoc/src/renderdoc-0.29/build'
make[3]: Wejście do katalogu '/home/marqin/renderdoc/src/renderdoc-0.29/build'
[  1%] Building CXX object renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/gl_common.cpp.o
[  1%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/spirv_disassemble.cpp.o
In file included from /home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/maths/formatpacking.h:158:0,
                 from /home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/driver/shaders/spirv/spirv_disassemble.cpp:26:
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/maths/half_convert.h: In function ‘float ConvertFromHalf(uint16_t)’:
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/maths/half_convert.h:125:20: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   return *(float*)&nan;
                    ^~~
[  2%] Building CXX object renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/gl_counters.cpp.o
[  2%] Building CXX object renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/gl_debug.cpp.o
In file included from /home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/maths/formatpacking.h:158:0,
                 from /home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/driver/gl/gl_debug.cpp:31:
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/maths/half_convert.h: In function ‘float ConvertFromHalf(uint16_t)’:
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/maths/half_convert.h:125:20: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   return *(float*)&nan;
                    ^~~
^Crenderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/build.make:110: polecenia dla obiektu 'renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/gl_debug.cpp.o' nie powiodły się
make[3]: *** [renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/gl_debug.cpp.o]: Przerwanie
CMakeFiles/Makefile2:190: polecenia dla obiektu 'renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/all' nie powiodły się
make[2]: *** [renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/all]: Przerwanie
renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/build.make:110: polecenia dla obiektu 'renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/spirv_disassemble.cpp.o' nie powiodły się
make[3]: *** [renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/spirv_disassemble.cpp.o]: Przerwanie
CMakeFiles/Makefile2:339: polecenia dla obiektu 'renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/all' nie powiodły się
make[2]: *** [renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/all]: Przerwanie
Makefile:83: polecenia dla obiektu 'all' nie powiodły się
make[1]: *** [all]: Przerwanie
Makefile:10: polecenia dla obiektu 'renderdoc' nie powiodły się
make: *** [renderdoc]: Przerwanie

==> BŁĄD: Aborted by user! Exiting...
==> BŁĄD: Wystąpił błąd w build().
    Przerywam...
```

**Comment by Marqin** [comment]
Compiler: GCC 6.1

I've tried trying another compiler, but there's another bug that Makefile ignores CPP/CXX variables.

**Comment by baldurk** [comment]
The CPP/CXX variables should work. That's how travis-ci seems to switch between [gcc](https://travis-ci.org/baldurk/renderdoc/jobs/133571184) and [clang](https://travis-ci.org/baldurk/renderdoc/jobs/133571185). It looks like it's using gcc 4.8 (and clang 3.5) so those are probably the only compilers I will keep working regularly for now, but I'll fix any other errors like this that crop up when they're reported.

**Comment by Marqin** [comment]
It builds fine with `clang` version 3.8. But according to [this github answer](http://stackoverflow.com/questions/7630150/dereferencing-type-punned-pointer-will-break-strict-aliasing-rules) this is Undefined behaviour and should error.

**Comment by Marqin** [comment]
edit, it doesn't build fine with clang 3.8, it errors in another place

**Comment by baldurk** [comment]
I think that should do the trick, but I can't test on gcc 6.1.

**Comment by Marqin** [comment]
That error was fixed, thanks.

**Comment by Marqin** [comment]
@baldurk it seems the same error is now in other file:

```
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/serialise/utf8printf.cpp:124:35: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
    argi = (int64_t)*(signed int*)&argu;
```

**Comment by baldurk** [comment]
Can you remove the line `-Werror` in the root CMakeLists.txt and rebuild, to collect all the warnings at once? rather than going one by one.

It might be a good idea though to use a similar version of compiler to the ones that travis-ci uses since otherwise it's quite possible it will break again in the future without me noticing.

**Comment by Marqin** [comment]
There are no more warnings/errors of this type apart from:
```
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/serialise/utf8printf.cpp: In function ‘void PrintInteger(bool, uint64_t, int, uint64_t, FormatterParams, bool, char*&, size_t&, char*)’:
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/serialise/utf8printf.cpp:124:35: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    argi = (int64_t)*(signed int*)&argu;
                                   ^~~~
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/serialise/utf8printf.cpp:130:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    argi = (int64_t)*(signed short*)&argu;
                                     ^~~~
```

but there are errors in jpeg-compressor.

**Comment by Marqin** [comment]
Oh. There are also some strict-aliasing errors in Vulkan:

```
[ 65%] Building CXX object renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/vk_replay.cpp.o
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/driver/vulkan/vk_replay.cpp: In member function ‘virtual void VulkanReplay::RenderMesh(uint32_t, const std::vector<MeshFormat>&, MeshDisplay)’:
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/driver/vulkan/vk_replay.cpp:1587:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   data->color = (Vec4f &)cfg.prevMeshColour;
                              ^~~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/driver/vulkan/vk_replay.cpp:1587:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/driver/vulkan/vk_replay.cpp: In member function ‘virtual void VulkanReplay::SavePipelineState()’:
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/driver/vulkan/vk_replay.cpp:3260:78: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
           dst.bindings[b].binds[a].offset += *(uint32_t *)&info[a].imageInfo.imageLayout;
                                                                              ^~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.29/renderdoc/driver/vulkan/vk_replay.cpp:3283:77: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          dst.bindings[b].binds[a].offset += *(uint32_t *)&info[a].imageInfo.imageLayout;
                                                                             ^~~~~~~~~~~

```

**Comment by baldurk** [comment]
I updated Arch and tried building - I ran into the jpeg-compressor warning but I didn't hit these for some reason. Either way, I've fixed the ones you mentioned.

**Comment by baldurk** [comment]
Closing this issue as the bug should be fixed in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!

**Comment by Marqin** [comment]
@baldurk it's still not working on GCC 6.1 (working on Clang 3.8), and I don't see button to reopen issue.

Here's error:
```
[ 37%] Building CXX object renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/vk_common.cpp.o
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkDeviceQueueCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:2807:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:2812:57: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   SerialisePODArray("pQueuePriorities", (uint32_t *&)el.pQueuePriorities, el.queueCount);
                                                         ^~~~~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkDeviceCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3058:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkBufferCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3135:51: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkBufferCreateFlagBits &)el.flags);
                                                   ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3137:50: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("usage", (VkBufferUsageFlagBits &)el.usage);
                                                  ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkBufferViewCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3163:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkImageCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3178:50: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkImageCreateFlagBits &)el.flags);
                                                  ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3186:49: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("usage", (VkImageUsageFlagBits &)el.usage);
                                                 ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkImageViewCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3213:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkSparseMemoryBind]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3230:55: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkSparseMemoryBindFlagBits &)el.flags);
                                                       ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkSparseImageMemoryBind]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3261:55: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkSparseMemoryBindFlagBits &)el.flags);
                                                       ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkFramebufferCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3338:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkAttachmentDescription]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3371:60: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkAttachmentDescriptionFlagBits &)el.flags);
                                                            ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkSubpassDescription]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3387:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3412:73: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   SerialisePODArray("preserveAttachments", (VkAttachmentReference *&)el.pPreserveAttachments,
                                                                         ^~~~~~~~~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkSubpassDependency]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3423:59: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("srcStageMask", (VkPipelineStageFlagBits &)el.srcStageMask);
                                                           ^~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3424:60: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("destStageMask", (VkPipelineStageFlagBits &)el.dstStageMask);
                                                            ^~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3425:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("srcAccessMask", (VkAccessFlagBits &)el.srcAccessMask);
                                                     ^~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3426:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("dstAccessMask", (VkAccessFlagBits &)el.dstAccessMask);
                                                     ^~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3427:59: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("dependencyFlags", (VkDependencyFlagBits &)el.dependencyFlags);
                                                           ^~~~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkRenderPassCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3438:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineVertexInputStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3524:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineInputAssemblyStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3542:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineTessellationStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3556:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineViewportStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3568:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineRasterizationStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3603:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineMultisampleStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3624:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineColorBlendStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3657:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineDepthStencilStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3678:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineDynamicStateCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3698:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkCommandPoolCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3712:56: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkCommandPoolCreateFlagBits &)el.flags);
                                                        ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkCommandBufferInheritanceInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3741:56: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("queryFlags", (VkQueryControlFlagBits &)el.queryFlags);
                                                        ^~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3742:74: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("pipelineStatistics", (VkQueryPipelineStatisticFlagBits &)el.pipelineStatistics);
                                                                          ^~~~~~~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkCommandBufferBeginInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3753:57: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkCommandBufferUsageFlagBits &)el.flags);
                                                         ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkQueryPoolCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3790:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3793:74: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("pipelineStatistics", (VkQueryPipelineStatisticFlagBits &)el.pipelineStatistics);
                                                                          ^~~~~~~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkSemaphoreCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3804:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkEventCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3815:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkFenceCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3826:50: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFenceCreateFlagBits &)el.flags);
                                                  ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkSamplerCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3837:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineShaderStageCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3863:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineCacheCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3931:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPipelineLayoutCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3960:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkShaderModuleCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:3997:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4006:40: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   SerialiseBuffer("pCode", (byte *&)el.pCode, sz);
                                        ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkImageSubresourceRange]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4024:55: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("aspectMask", (VkImageAspectFlagBits &)el.aspectMask);
                                                       ^~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkImageSubresourceLayers]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4036:55: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("aspectMask", (VkImageAspectFlagBits &)el.aspectMask);
                                                       ^~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkImageSubresource]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4047:55: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("aspectMask", (VkImageAspectFlagBits &)el.aspectMask);
                                                       ^~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkMemoryBarrier]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4072:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("srcAccessMask", (VkAccessFlagBits &)el.srcAccessMask);
                                                     ^~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4073:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("dstAccessMask", (VkAccessFlagBits &)el.dstAccessMask);
                                                     ^~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkBufferMemoryBarrier]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4084:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("srcAccessMask", (VkAccessFlagBits &)el.srcAccessMask);
                                                     ^~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4085:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("dstAccessMask", (VkAccessFlagBits &)el.dstAccessMask);
                                                     ^~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkImageMemoryBarrier]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4103:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("srcAccessMask", (VkAccessFlagBits &)el.srcAccessMask);
                                                     ^~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4104:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("dstAccessMask", (VkAccessFlagBits &)el.dstAccessMask);
                                                     ^~~~~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkGraphicsPipelineCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4123:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkPipelineCreateFlagBits &)el.flags);
                                                     ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkComputePipelineCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4236:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkPipelineCreateFlagBits &)el.flags);
                                                     ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkDescriptorPoolCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4275:59: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkDescriptorPoolCreateFlagBits &)el.flags);
                                                           ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkPushConstantRange]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4435:55: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("stageFlags", (VkShaderStageFlagBits &)el.stageFlags);
                                                       ^~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkDescriptorSetLayoutBinding]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4448:55: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("stageFlags", (VkShaderStageFlagBits &)el.stageFlags);
                                                       ^~~~~~~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkDescriptorSetLayoutCreateInfo]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4479:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp: In member function ‘void Serialiser::Serialise(const char*, T&) [with T = VkSwapchainCreateInfoKHR]’:
/home/marqin/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_common.cpp:4582:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Serialise("flags", (VkFlagWithNoBits &)el.flags);
                                             ^~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/build.make:63: renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/vk_common.cpp.o] Błąd 1
make[3]: Opuszczenie katalogu '/home/marqin/renderdoc/src/renderdoc-0.30/build'
make[2]: *** [CMakeFiles/Makefile2:248: renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/all] Błąd 2
make[2]: *** Oczekiwanie na niezakończone zadania....
make[3]: Opuszczenie katalogu '/home/marqin/renderdoc/src/renderdoc-0.30/build'
[ 37%] Built target rdoc_gl
make[2]: Opuszczenie katalogu '/home/marqin/renderdoc/src/renderdoc-0.30/build'
make[1]: *** [Makefile:84: all] Błąd 2
make[1]: Opuszczenie katalogu '/home/marqin/renderdoc/src/renderdoc-0.30/build'
make: *** [Makefile:10: renderdoc] Błąd 2
==> BŁĄD: Wystąpił błąd w build().
    Przerywam...
```

**Comment by baldurk** [comment]
Hey, looks like I misunderstood github's permissions - you can only re-open an issue that you closed yourself, not one that I closed. I've re-opened it.

One of those is valid (vk_common.cpp:2812) but the others are nonsense. I'm not going to add a whole bunch of boilerplate to keep GCC happy, so I'll probably just disable the warning on that file.

I have a refactored serialisation system which will be coming at some point, and that should remove the need for all this enum casting and compile warning-free.

**Comment by baldurk** [comment]
I built with gcc 6.1:
```
$ g++-6 -v
gcc version 6.1.1 20160510 (Ubuntu 6.1.1-2ubuntu12~16.04)
```

And I didn't get any of the warnings. I'm not sure if it's specific to some sub-sub-version or something. Either way, I fixed the legitimate problem an then removed the warning (hopefully I got that right - I can't test it).

**Comment by Marqin** [comment]
It's still not working for me, after applying those two commits to 0.30:

```
[ 28%] Building CXX object renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/vk_debug.cpp.o
/build/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_debug.cpp: In member function 'ResourceId VulkanDebugManager::RenderOverlay(ResourceId, TextureDisplayOverlay, uint32_t, const std::vector<unsigned int, std::allocator<unsigned int> >&)':
/build/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_debug.cpp:4394:32: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
       ubo->ViewRect = (Vec4f &)viewport;
                                ^~~~~~~~
/build/renderdoc/src/renderdoc-0.30/renderdoc/driver/vulkan/vk_debug.cpp:4394:32: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
cc1plus: all warnings being treated as errors
make[3]: *** [renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/build.make:135: renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/vk_debug.cpp.o] Error 1
make[3]: Leaving directory '/build/renderdoc/src/renderdoc-0.30/build'
make[2]: *** [CMakeFiles/Makefile2:248: renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by baldurk** [comment]
That one is probably valid too, I can fix that but it's wasteful going back and forth playing whack-a-mole with you letting me know of new warnings.

Do you know why I can't see those warnings myself? Is there some gcc configuration outside of the make process? A global setting or something to enable or suppress certain warnings.

I think I have an archlinux VM I can try and update and try and build on, in case maybe it's some archlinux-specific compile options to gcc or other.

**Comment by Marqin** [comment]
GCC by default uses `-fstrict-aliasing` and uses `-Wstrict-aliasing` in `-Wall`. Maybe your GCC comes with disabled strict-aliasing? Try compiling with `-fstrict-aliasing`.

**Comment by Marqin** [comment]
Oh, `-fstrict-aliasing` is on default only with `-O2 -O3 -Os` options according to GCC docs.

**Comment by Marqin** [comment]
> going back and forth playing whack-a-mole with you letting me know of new warnings

I think it could be somehow possible to setup ArchLinux docker image in Travis CI for tests.

**Comment by baldurk** [comment]
OK I've got it, after you mentioned that it's enabled with the `-O` options. I get the errors as long as I add `-DCMAKE_BUILD_TYPE=Release` to the cmake command line. I'm still unfamiliar with CMake and don't have a particularly sophisticated understanding of building on linux these days, so I didn't think that would make any difference to warning status.

I think there's a few things to do here:

1. Enable `-fstrict-aliasing` for all builds, so that we don't have new warnings appearing in release builds (I also had `-Wunused-result` errors appearing).
2. Fix the current warnings with that
3. Disable `-Werror` for release builds. The only reason for `-Werror` is so that during development warnings don't sneak in. External builders shouldn't have to worry about the code being warning free on all possibly compiler version/distro variants. I'll probably start doing linux builds some time soon (although packaging is a nightmare I have not yet gone anywhere near - for now it's probably just going to be binary tarballs).
4. Expand the travis builds. At least we should have one release build happening to check if maybe more warnings get added in release/optimised mode only. I'd be happy to have at least one archlinux entry in the matrix (ideally in development so it errors on warnings to keep them in check), but my understanding of travis is that it [only supports ubuntu images](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments)?

I'll do 1. and 2. today, and look at sorting 3. this week or next. 4. is more up in the air - I'd welcome any PRs to improve the travis build checking, right now the builds are fast and not regular, so we're not in danger of over-using travis and running into fair use limits on the free plan.

**Comment by Marqin** [comment]
1. :+1: 
2. :+1: 
3. I don't agree. Such errors can be helpful narrowing some platform-dependent bugs.
4. [this](https://docs.travis-ci.com/user/docker/) + [this](https://hub.docker.com/r/base/archlinux/)

I could help with 4, but I really don't like configuring .travis.yml. Maybe it would be easier to create ready image for testing this app and just `run` it from travis.

**Comment by Marqin** [comment]
Also 4. could be done with `chroot` with ArchLinux install, but I think that would be much slower than Docker image.

**Comment by baldurk** [comment]
I'm afraid I am absolutely unfamiliar with docker, so I'm not really sure what that entails. That's why I didn't know how you'd configure an arch build target, or whether it's feasible within travis.

I still think removing `-Werror` from code that will be compiled by distributions/packages is the right thing to do. The only reason I currently have `-Werror` is that the linux code isn't mature enough to be worth distributing. That's hopefully going to change soon so this was inevitable.

On linux it's just completely impossible to reliably predict what warnings will occur or what code will trip compiler up in the wild, and making that a blocking problem for end-users is pushing it in the wrong direction. It just means non-developers compiling the code will need to hack it locally to either disable the warning (in effect achieving the same thing as removing `-Werror`) or worse still try to fix the warning in code and maybe do the wrong thing. Warnings should definitely still be enabled in release builds so they can be reported back upstream as relevant, but they shouldn't block builds.

**Comment by baldurk** [comment]
Tested building on release from both gcc-6.1 and clang-3.8, please check but I think it should be compiling cleanly now.

**Comment by Marqin** [comment]
I've cherry-picked commits 224e20a, 6c30a55, 733ed8d, bee280e, d6d36f6 and applied them to 0.30 package and it compiles now with GCC 6.1.1 and Clang 3.8 👍

**Comment by baldurk** [comment]
Great :). At some point probably after v0.31 I'll create an issue as a request for input on linux packaging. At the moment it's not a high priority since right now the linux version isn't really useful to anyone, but I do want to make sure the repository is structured in such a way as to be friendly to packagers and downstream maintainers (should any other than yourself appear!).
