### ISSUE TITLE
Crash when accessing the backbuffer through the swapchain (for Direct2D)

### ISSUE THREAD

**Issue by AvengerDr** [baldurk/renderdoc#402]
Hi, I was trying to use RenderDoc to capture a frame in my application. The application (which uses the Xenko engine) runs fine on its own, but crashes at a specific point when running through Renderdoc.

Specifically it gives this error:
`Error: Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x80004002], Module: [General], ApiCode: [E_NOINTERFACE/No such interface supported], Message: No such interface supported`

The line at fault is the following:
`swapChain.GetBackBuffer<Surface2>(0);`

I need the interface returned from that command to create a surface needed to render Direct2D content. I wanted to see why nothing was being rendered on it. As mentioned, when running on its own it does not crash there and I can see the surface when debugging, but RenderDoc crashes there.

I'm guessing it could have something to do with the particular DirectX feature level not supporting that interface?

**Comment by AvengerDr** [comment]
**Edit:** Diagnostic log
`RDOC: [12:51:54]             core.cpp( 309) - Log     - RenderDoc v0.32 x64 (ae06f86a1c9b892bf518cade3524f3f4e250e437) loaded in replay application
RDOC: [12:52:22]    win32_process.cpp( 480) - Log     - Injecting renderdoc into process 6100
RDOC: [12:52:23]   target_control.cpp( 409) - Log     - Got remote handshake: Test () [6100]
RDOC: [12:59:02]    win32_network.cpp( 178) - Warning - recv: 10054`

**Comment by baldurk** [comment]
Hi, the diagnostic log you posted is from the replay application. While the application is running (or if it crashes and doesn't shut down cleanly) there will be a similarly named file in the same folder like `RenderDoc_app_<date>_<time>.log` which will have more useful information.

In this case in particular, some QueryInterface somewhere is failing. I don't know exactly which one, but I imagine it's because I'm not properly handling the interception of those interfaces and either I'm returning E_NOINTERFACE explicitly somewhere for an unsupported interface or the underlying DX code is getting confused and returning it somewhere.

Realistically, actually debugging Direct2D is outside the scope of this project. It's possible I could make it at least run so you can debug the D3D parts of a program that's using it. For that I'd need an example program that's using both APIs together, if you can provide one either yourself or link to a sample online that's representative that would be quite helpful.

**Comment by AvengerDr** [comment]
Thanks for the prompt reply! Unfortunately I cannot find any log in the folder (there's nothing in the AppData/Roaming either). Concerning an interop sample you could either try the [SharpDX samples](https://github.com/sharpdx/SharpDX-Samples) or this MSDN Direct3D/Direct2D [interop sample](https://code.msdn.microsoft.com/windowsapps/Direct2D-Direct3D-Interop-ee641e46).

I tried SharpDX's "MiniRect" sample and it exhibits the same problem as nothing happens after I press capture. However I cannot see any stacktrace but I guess the problem must be a similar one. The sequence of commands they are using is very similar to my own. The MSDN sample runs on W8.1 so I was not able to compile it (i'm on W10) but it is in C++ if you prefer that.

I understand debugging D2D might be outside your project's scope. When I used the VS graphics debugger I observed that D2D's call seem to be "converted" into D3D calls so I was still able to see what was being rendered. However, VS's debugger stopped working recently: when I launch it says that the Capture layer appears to be hung, so I hoped Renderdoc would let me see what was going on.

**Comment by baldurk** [comment]
OK I think I have sorted it out, I was able to capture the Direct2D1 samples from SharpDX:

![image](https://cloud.githubusercontent.com/assets/661798/19684725/267307d2-9ab9-11e6-8e3b-6595f4c32d44.png)

It turned out that all that was missing was the `QueryInterface` call from `IDXGIDevice` to return the D3D11 device. I was handling any queries for the base `ID3D11Device` interface, but it seems that D2D will query for `ID3D11Device1`. Anyway, that should be handled now.

Let me know how it goes for you on your program.

**Comment by AvengerDr** [comment]
Hi, does the latest nightly build incorporate this change? Because it's still not working for me. I tried version `RenderDoc v0.32 x64 (7e2296911cfe160cbf1ca72795142a6db7c19c58)`.

**Comment by baldurk** [comment]
Yes the latest nightly includes this fix. If it's still not working for you I'll need more information to repro.

I tested with the SharpDX samples you linked to and they work OK for me, are they breaking on your machine? I can't run the MSDN interop sample because it's some kind of windows store bollocks. Maybe you're doing something additional that's not included in those samples?

**Comment by AvengerDr** [comment]
Hi, I've uploaded the executable of my D2D project [here](http://www.megafileupload.com/c1n5/Xenko_D2DTest.zip). It should just draw a purple square in the top left part of the screen. Let me know if that runs, otherwise I'll send you the sources.

**Comment by baldurk** [comment]
When I ran your program I found it wouldn't run for me on win7 (not sure if you're aware or not?). When I went to go test on win10, I found that D2D behaves quite differently there and the SharpDX samples were failing. I fixed the issues that I found and your sample seems to capture for me now. Hopefully it should fix the issues you've found, but let me know again how you get on :smile:.

**Comment by youaresoomean** [comment]
Hi, tried nightly build from nov '14 with our D2D1 based application - unfortunately still fails to get the backbuffer with (0x80004002)
```
sys::com_ptr<IDXGISurface> dxgiBackBuffer;
hr = swapChain_->GetBuffer(0, IID_PPV_ARGS(&dxgiBackBuffer));
```

**Comment by baldurk** [comment]
That isn't specifically D2D related I don't think. The query for `IDXGISurface` in `GetBuffer` will fail deliberately - I need to know the specific type of texture requested, whether it's D3D10, D3D11, D3D12 or some other funky type. Because of the capture setup and object wrapping, e.g. I don't support D3D10 and 11/12 are entirely separate implementations, so I can't cast between them later if I guess the wrong one.

As always, the MSDN documentation on `GetBuffer` is _completely_ worthless and it doesn't give any information on whether or not this should be legal, or just happens to work by coincidence.

What I can do is use the device that was passed when creating the swapchain to determine the type, if a D3D11 or D3D12 device was passed. I don't know for sure if that means the backbuffer will be in the same format, but it's a "better than nothing" guess that will work in most cases. I'd suggest it would be safer though to be more explicit to your code and request a `ID3D11Texture2D` and then `QueryInterface` for the `IDXGISurface`.

**Comment by youaresoomean** [comment]
@baldurk You were right - changing the GetBuffer type to ID3D11Texture2D did the trick! Amazing - thanks alot!

**Comment by baldurk** [comment]
I believe the D2D issues that I'm aware of or had repros for are resolved in v0.32. If something's still not right in the latest build then let me know and I'll re-open and investigate.
