### ISSUE TITLE
Crash when debugging D3D11 log

### ISSUE THREAD

**Issue by mellinoe** [baldurk/renderdoc#789]
First of all, I'd like to say thanks -- RenderDoc has been invaluable for debugging and learning. I use it on a daily basis, and it's a great tool.

I'm currently in the middle of a rewrite of my graphics library, and as usual I would love to debug it with RenderDoc. At some point, I've started to hit a crash whenever I load up a log from my D3D11 renderer. Using a "Development" version of RenderDoc (on the v0.x and the v1.x branches), I see that an assertion is hit here:

https://github.com/baldurk/renderdoc/blob/v0.x/renderdoc/driver/d3d11/d3d11_context.cpp#L2014

The immediate reason for this is that `NumUAVs` is extremely large -- `4294967295`. I don't exactly know why that is, or even if it's important -- perhaps it's a red herring.

I'm happy to provide any extra information or repro binaries if necessary.

**Comment by mmusu3** [comment]
This looks like it may have been fixed recently in 0.x f62f281415d81bee8728b7530335ce01e707d801 and 1.x 8f4b2a0d4959da2fe8f9b1590eaff63bf4f86da8 branches.
4294967295 is -1 or D3D11_KEEP_UNORDERED_ACCESS_VIEWS

**Comment by mellinoe** [comment]
Hm, that does look like it could be related. I have tested with the tip of both branches (so I should have those fixes), but I will re-build everything to make sure.

**Comment by mellinoe** [comment]
It is indeed still happening, even with those changes. I can't help but notice, though -- is this check wrong?

```C++
  if(NumRTVs != D3D11_KEEP_UNORDERED_ACCESS_VIEWS)
    NumSlots += NumUAVs;
```

Shouldn't the check instead be `NumUAVs != D3D11_KEEP_UNORDERED_ACCESS_VIEWS` ?

**Comment by mellinoe** [comment]
That does indeed fix the issue. Thanks for the pointer @mmusu3

**Comment by baldurk** [comment]
Yep, that's a copy-paste fail on my part! Thanks for catching it.

**Comment by baldurk** [comment]
Pushed a fix on v0.x and v1.x. I'll close this issue since you already confirmed the fix, but let me know if you run into other problems.
